# Generated by Django 4.0.1 on 2022-02-28 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_message_options_conversation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='MesssageConversation',
        ),
    ]
