# Generated by Django 4.0.1 on 2022-03-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_messsageconversation_expediteur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MesssageConversation',
            new_name='MessageConversation',
        ),
    ]
